In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.contrib import rnn
import pprint

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [2]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [3]:
with tf.variable_scope('one_cell') as scope:
    hidden_size = 2
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    print(cell.output_size, cell.state_size)
    
    x_data = np.array([[h]], dtype=np.float32)
    pp.pprint(x_data)
    outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

2 2
array([[[ 1.,  0.,  0.,  0.]]], dtype=float32)
array([[[-0.34207192, -0.37725964]]], dtype=float32)


In [4]:
with tf.variable_scope('two_sequences') as scope:
    hidden_size = 2
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    x_data = np.array([[h, e, l, l, o]], dtype=np.float32)
    print(x_data.shape)
    pp.pprint(x_data)
    outputs, states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

(1, 5, 4)
array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]]], dtype=float32)
array([[[ 0.58423001, -0.5375849 ],
        [ 0.59127146,  0.4859907 ],
        [-0.0392063 ,  0.16300848],
        [-0.3251566 , -0.24151269],
        [ 0.30082983,  0.44860023]]], dtype=float32)


In [5]:
with tf.variable_scope('3_batches') as scope:
    x_data = np.array([[h, e, l, l, o],
                       [e, o, l, l, l],
                       [l, l, e, e, l]], dtype=np.float32)
    pp.pprint(x_data)
    
    hidden_size = 2
    cell = rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)
    outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)
array([[[ 0.07993083,  0.02655499],
        [ 0.00993129, -0.04933615],
        [-0.08108633,  0.15016098],
        [-0.13863124,  0.26287022],
        [-0.14915149,  0.16527644]],

       [[-0.03775665, -0.06741977],
        [-0.05529733,  0.02535583],
        [-0.12305787,  0.2072483 ],
        [-0.165277  ,  0.29360244],
        [-0.19387284,  0.33663443]],

       [[-0.08715235,  0.17937568],
        [-0.14213853,  0.27757668],
        [-0.12831488,  0.11961386],
        [-0.12538558,  0.0229494 ],
        [-0.1780429 ,

In [6]:
with tf.variable_scope('3_batches_dynamic_length') as scope:
    x_data = np.array([[h, e, l, l, o],
                       [e, o, l, l, l],
                       [l, l, e, e, l]], dtype=np.float32)
    pp.pprint(x_data)
    
    hidden_size = 2
    cell = rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)
    outputs, _states = tf.nn.dynamic_rnn(cell, x_data, sequence_length=[5, 3, 4], dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)
array([[[ 0.16696437,  0.0432712 ],
        [ 0.06824089,  0.0398255 ],
        [ 0.08222457, -0.03338977],
        [ 0.10755513, -0.07713157],
        [ 0.15172601, -0.09094683]],

       [[-0.07663952, -0.01420865],
        [ 0.02604416, -0.03502907],
        [ 0.06478477, -0.0715    ],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ]],

       [[ 0.04150204, -0.05916769],
        [ 0.07612916, -0.09773878],
        [-0.0007597 , -0.12512194],
        [-0.07672381, -0.12729944],
        [ 0.        ,

In [7]:
with tf.variable_scope('initial_state') as scope:
    batch_size = 3
    x_data = np.array([[h, e, l, l, o],
                       [e, o, l, l, l],
                       [l, l, e, e, l]], dtype=np.float32)
    pp.pprint(x_data)
    
    hidden_size = 2
    cell = rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)
    initial_state = cell.zero_state(batch_size, tf.float32)
    outputs, _states = tf.nn.dynamic_rnn(cell, x_data, initial_state=initial_state, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)
array([[[-0.13632436, -0.09421622],
        [ 0.02161353, -0.1221822 ],
        [ 0.00844346, -0.0097941 ],
        [-0.00026899,  0.10190561],
        [-0.15481962,  0.16147412]],

       [[ 0.09798151, -0.0751311 ],
        [-0.06410061,  0.03721715],
        [-0.03405155,  0.14896131],
        [-0.03160052,  0.21274975],
        [-0.03171949,  0.25567728]],

       [[-0.00592484,  0.1096272 ],
        [-0.01221933,  0.18544333],
        [ 0.07900649,  0.0210842 ],
        [ 0.15140842, -0.06046054],
        [ 0.07668705,

In [8]:
batch_size = 3
sequence_length = 5
input_dim = 3

x_data = np.arange(45, dtype=np.float32).reshape(batch_size, sequence_length, input_dim)
pp.pprint(x_data)

array([[[  0.,   1.,   2.],
        [  3.,   4.,   5.],
        [  6.,   7.,   8.],
        [  9.,  10.,  11.],
        [ 12.,  13.,  14.]],

       [[ 15.,  16.,  17.],
        [ 18.,  19.,  20.],
        [ 21.,  22.,  23.],
        [ 24.,  25.,  26.],
        [ 27.,  28.,  29.]],

       [[ 30.,  31.,  32.],
        [ 33.,  34.,  35.],
        [ 36.,  37.,  38.],
        [ 39.,  40.,  41.],
        [ 42.,  43.,  44.]]], dtype=float32)


In [9]:
with tf.variable_scope('generated_data') as scope:
    cell = rnn.BasicLSTMCell(num_units=5, state_is_tuple=True)
    initial_state = cell.zero_state(batch_size, tf.float32)
    outputs, _states = tf.nn.dynamic_rnn(cell, x_data, initial_state=initial_state, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[ -2.44120285e-01,  -7.63444826e-02,   1.33687362e-01,
           4.64775413e-02,   7.01354444e-02],
        [ -4.12501305e-01,  -7.35506952e-01,   1.26858279e-01,
          -1.83150679e-01,   4.47253175e-02],
        [ -4.09041315e-01,  -8.46783221e-01,   1.09484509e-01,
          -4.98025954e-01,   1.72434840e-02],
        [ -3.52916926e-01,  -8.19680572e-01,   7.92364106e-02,
          -7.54185736e-01,   5.35760447e-03],
        [ -3.01116019e-01,  -7.86500812e-01,   5.29572032e-02,
          -8.91687751e-01,   1.56865991e-03]],

       [[ -1.73362449e-01,  -7.61593819e-01,   9.17433772e-06,
          -5.78989863e-01,   8.12268809e-06],
        [ -2.10794017e-01,  -7.64800787e-01,   9.40091195e-06,
          -8.57091248e-01,   3.21391167e-06],
        [ -1.74150214e-01,  -7.62930036e-01,   6.17352953e-06,
          -9.55860555e-01,   1.01014393e-06],
        [ -1.30957305e-01,  -7.62116611e-01,   3.81032009e-06,
          -9.86610830e-01,   3.09567298e-07],
        [ -8.7706

In [10]:
with tf.variable_scope('MultiRNNCell') as scope:
    cell = rnn.BasicLSTMCell(num_units=5, state_is_tuple=True)
    cell = rnn.MultiRNNCell([cell] * 3, state_is_tuple=True)
    
    outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    print("Dynamic RNN: ", outputs)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

ValueError: Dimensions must be equal, but are 10 and 8 for 'MultiRNNCell/rnn/while/rnn/multi_rnn_cell/cell_0/cell_0/basic_lstm_cell/MatMul_1' (op: 'MatMul') with input shapes: [3,10], [8,20].